services:
  - type: web
    name: eleodoro-distribuidora
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_SQLITE_FALLBACK
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: GMAIL_USER
        value: vitrinazo.cl@gmail.com
      - key: GMAIL_PASS
        value: mxec vkjr jbae czez

